"""Topology configuration key constants."""

# Topology base config keys
ALL_C_CONNECT = "cconnections"
ALL_C_CHANNEL = "cchannels"
ALL_NODE = "nodes"
ALL_Q_CONNECT = "qconnections"
ALL_Q_CHANNEL = "qchannels"
ATTENUATION = "attenuation"
CONNECT_NODE_1 = "node1"
CONNECT_NODE_2 = "node2"
DELAY = "delay"
DISTANCE = "distance"
DST = "destination"
NAME = "name"
SEED = "seed"
SRC = "source"
STOP_TIME = "stop_time"
TRUNC = "truncation"
TYPE = "type"
ALL_TEMPLATES = "templates"
TEMPLATE = "template"
GATE_FIDELITY = "gate_fidelity"
MEASUREMENT_FIDELITY = "measurement_fidelity"
FORMALISM = "formalism"

# RouterNetTopo config keys
BSM_NODE = "BSMNode"
MEET_IN_THE_MID = "meet_in_the_middle"
MEMO_ARRAY_SIZE = "memo_size"
PORT = "port"
PROC_NUM = "process_num"
QUANTUM_ROUTER = "QuantumRouter"
CONTROLLER = "Controller"

# QKDTopo config keys
QKD_NODE = "QKDNode"

# QlanStarTopo config keys
ORCHESTRATOR = "QlanOrchestratorNode"
CLIENT = "QlanClientNode"
LOCAL_MEMORIES = "local_memories"
CLIENT_NUMBER = "client_number"
MEM_FIDELITY_ORCH = "memo_fidelity_orch"
MEM_FREQUENCY_ORCH = "memo_frequency_orch"
MEM_EFFICIENCY_ORCH = "memo_efficiency_orch"
MEM_COHERENCE_ORCH = "memo_coherence_orch"
MEM_WAVELENGTH_ORCH = "memo_wavelength_orch"
MEM_FIDELITY_CLIENT = "memo_fidelity_client"
MEM_FREQUENCY_CLIENT = "memo_frequency_client"
MEM_EFFICIENCY_CLIENT = "memo_efficiency_client"
MEM_COHERENCE_CLIENT = "memo_coherence_client"
MEM_WAVELENGTH_CLIENT = "memo_wavelength_client"
MEASUREMENT_BASES = "measurement_bases"
MEM_SIZE = "memo_size"

# DQCNetTopo config keys
DQC_NODE = "DQCNode"
DATA_MEMO_ARRAY_SIZE = "data_memo_size"
