
from .topology import Topology as Topo
from .node import QKDNode
from ..constants import *


class QKDTopo(Topo):
    """Class for generating QKD network

    Class QKDTopo is the child of class Topology. QKD nodes, quantum channels,
    classical channels and timeline for simulation could be generated by using
    this class.

    Attributes:
        nodes (dict[str, list[Node]]): mapping of type of node to a list of same type node.
        qchannels (list[QuantumChannel]): list of quantum channel objects in network.
        cchannels (list[ClassicalChannel]): list of classical channel objects in network.
        tl (Timeline): the timeline used for simulation
    """

    def _build(self, config: dict):
        self._add_timeline(config)
        self._add_nodes(config)
        self._add_qchannels(config)
        self._add_cchannels(config)
        self._add_cconnections(config)

    def _add_nodes(self, config):
        for node in config[ALL_NODE]:
            # TODO: add encoding configuration for QKD nodes
            seed = node[SEED]
            node_type = node[TYPE]
            name = node[NAME]
            template_name = node.get(TEMPLATE, None)
            template = self.templates.get(template_name, {})

            if node_type == QKD_NODE:
                node = QKDNode(name, self.tl,
                               seed=seed, component_templates=template)
            else:
                raise NotImplementedError("Unknown type of node")

            if node_type in self.nodes:
                self.nodes[node_type].append(node)
            else:
                self.nodes[node_type] = [node]
