import json
import numpy as np

from .topology import Topology as Topo
from ..kernel.timeline import Timeline
from ..constants import SPEED_OF_LIGHT
from .const_topo import (
    MEET_IN_THE_MID, ORCHESTRATOR, CLIENT, LOCAL_MEMORIES, CLIENT_NUMBER,
    MEM_FIDELITY_ORCH, MEM_FREQUENCY_ORCH, MEM_EFFICIENCY_ORCH,
    MEM_COHERENCE_ORCH, MEM_WAVELENGTH_ORCH,
    MEM_FIDELITY_CLIENT, MEM_FREQUENCY_CLIENT, MEM_EFFICIENCY_CLIENT,
    MEM_COHERENCE_CLIENT, MEM_WAVELENGTH_CLIENT,
    MEASUREMENT_BASES, MEM_SIZE,
    STOP_TIME, ALL_NODE, SEED, TYPE, NAME, TEMPLATE,
    ALL_Q_CONNECT, CONNECT_NODE_1, CONNECT_NODE_2, ATTENUATION, DISTANCE,
    ALL_C_CHANNEL, SRC, DST, DELAY, ALL_C_CONNECT,
)

from .qlan.orchestrator import QlanOrchestratorNode
from .qlan.client import QlanClientNode


class QlanStarTopo(Topo):
    """Class for generating qlan topology with a single orchestrator and multiple clients

    Class QlanStarTopo is the child of class Topology. Orchestrator nodes, Client nodes, quantum  channels,
    classical channels and timeline for simulation could be generated by using this class.

    Attributes:
        nodes (dict[str, list[Node]]): mapping of type of node to a list of same type node.
        qchannels (list[QuantumChannel]): list of quantum channel objects in network.
        cchannels (list[ClassicalChannel]): list of classical channel objects in network.
        tl (Timeline): the timeline used for simulation
        orchestrator_nodes (list[QlanOrchestratorNode]): list of orchestrator nodes in the network.
        client_nodes (list[QlanClientNode]): list of client nodes in the network.
        remote_memories_array (list[Memory]): list of remote memory objects in the network.
        n_local_memories (int): number of local memories in each orchestrator node.
        n_clients (int): number of client nodes in the network.
        meas_bases (str): measurement bases used by the client nodes.
        memo_fidelity_orch (float): fidelity of the memories in the orchestrator nodes.
        memo_freq_orch (int): frequency of the memories in the orchestrator nodes.
        memo_efficiency_orch (float): efficiency of the memories in the orchestrator nodes.
        memo_coherence_orch (float): coherence of the memories in the orchestrator nodes.
        memo_wavelength_orch (int): wavelength of the memories in the orchestrator nodes.
        memo_fidelity_client (float): fidelity of the memories in the client nodes.
        memo_freq_client (int): frequency of the memories in the client nodes.
        memo_efficiency_client (float): efficiency of the memories in the client nodes.
        memo_coherence_client (float): coherence of the memories in the client nodes.
        memo_wavelength_client (int): wavelength of the memories in the client nodes.
    """
    _deprecated_attrs = {
        "MEET_IN_THE_MID": MEET_IN_THE_MID,
        "ORCHESTRATOR": ORCHESTRATOR,
        "CLIENT": CLIENT,
        "LOCAL_MEMORIES": LOCAL_MEMORIES,
        "CLIENT_NUMBER": CLIENT_NUMBER,
        "MEM_FIDELITY_ORCH": MEM_FIDELITY_ORCH,
        "MEM_FREQUENCY_ORCH": MEM_FREQUENCY_ORCH,
        "MEM_EFFICIENCY_ORCH": MEM_EFFICIENCY_ORCH,
        "MEM_COHERENCE_ORCH": MEM_COHERENCE_ORCH,
        "MEM_WAVELENGTH_ORCH": MEM_WAVELENGTH_ORCH,
        "MEM_FIDELITY_CLIENT": MEM_FIDELITY_CLIENT,
        "MEM_FREQUENCY_CLIENT": MEM_FREQUENCY_CLIENT,
        "MEM_EFFICIENCY_CLIENT": MEM_EFFICIENCY_CLIENT,
        "MEM_COHERENCE_CLIENT": MEM_COHERENCE_CLIENT,
        "MEM_WAVELENGTH_CLIENT": MEM_WAVELENGTH_CLIENT,
        "MEASUREMENT_BASES": MEASUREMENT_BASES,
        "MEM_SIZE": MEM_SIZE,
    }

    def __init__(self, conf_file_name: str):
        self.orchestrator_nodes = []
        self.client_nodes = []
        self.remote_memories_array = []
        super().__init__(conf_file_name)


    
    def _add_parameters(self, config: dict):

        self.n_local_memories = config.get(LOCAL_MEMORIES, 1)
        self.n_clients = config.get(CLIENT_NUMBER, 1)
        self.meas_bases = config.get(MEASUREMENT_BASES, 'zz')

        self.memo_fidelity_orch = config.get(MEM_FIDELITY_ORCH, 0.9)
        self.memo_freq_orch = config.get(MEM_FREQUENCY_ORCH, 2000)
        self.memo_efficiency_orch = config.get(MEM_EFFICIENCY_ORCH, 1)
        self.memo_coherence_orch = config.get(MEM_COHERENCE_ORCH, -1)
        self.memo_wavelength_orch = config.get(MEM_WAVELENGTH_ORCH, 500)

        self.memo_fidelity_client = config.get(MEM_FIDELITY_CLIENT, 0.9)
        self.memo_freq_client = config.get(MEM_FREQUENCY_CLIENT, 2000)
        self.memo_efficiency_client = config.get(MEM_EFFICIENCY_CLIENT, 1)
        self.memo_coherence_client = config.get(MEM_COHERENCE_CLIENT, -1)
        self.memo_wavelength_client = config.get(MEM_WAVELENGTH_CLIENT, 500)

    def _add_nodes(self, config: dict):
        self._add_client_nodes(config)
        self._add_orchestrator_nodes(config)

    def _add_client_nodes(self, config: dict):
        for node in config[ALL_NODE]:
            seed = node[SEED]
            node_type = node[TYPE]
            name = node[NAME]
            template_name = node.get(TEMPLATE, None)
            template = self.templates.get(template_name, {})

            if node_type == CLIENT:
                node_obj = QlanClientNode(name,
                                            self.tl,
                                            1,
                                            self.memo_fidelity_client,
                                            self.memo_freq_client,
                                            self.memo_efficiency_client,
                                            self.memo_coherence_client,
                                            self.memo_wavelength_client)
                node_obj.set_seed(seed)
                node_memo = node_obj.get_components_by_type("Memory")[0]
                self.remote_memories_array.append(node_memo)
                self.client_nodes.append(node_obj)
                self.nodes[node_type].append(node_obj)

            elif node_type == ORCHESTRATOR:
                pass

            else:
                raise ValueError(f"Unknown type of node '{node_type}'")

            
    def _add_orchestrator_nodes(self, config: dict):
        for node in config[ALL_NODE]:
            seed = node[SEED]
            node_type = node[TYPE]
            name = node[NAME]
            template_name = node.get(TEMPLATE, None)
            template = self.templates.get(template_name, {})

            if node_type == ORCHESTRATOR:
                node_obj = QlanOrchestratorNode(name, 
                                                self.tl,
                                                self.n_local_memories, 
                                                self.remote_memories_array, self.memo_fidelity_orch, 
                                                self.memo_freq_orch, 
                                                self.memo_efficiency_orch, 
                                                self.memo_coherence_orch, 
                                                self.memo_wavelength_orch)
                node_obj.set_seed(seed)
                node_obj.update_bases(self.meas_bases)
                self.orchestrator_nodes.append(node_obj)
                self.nodes[node_type].append(node_obj)
            
            elif node_type == CLIENT:
                pass

            else:
                raise ValueError(f"Unknown type of node '{node_type}'")

    def _add_protocols(self):
        for orch in self.orchestrator_nodes:
            orch.resource_manager.create_protocol()
        for client in self.client_nodes:
            client.resource_manager.create_protocol()

    def _add_qconnections(self, config: dict):
        '''generate bsm_info, qc_info, and cc_info for the q_connections
        '''
        for q_connect in config.get(ALL_Q_CONNECT, []):
            node1 = q_connect[CONNECT_NODE_1]
            node2 = q_connect[CONNECT_NODE_2]
            attenuation = q_connect[ATTENUATION]
            distance = q_connect[DISTANCE] // 2
            channel_type = q_connect[TYPE]
            cc_delay = []
            for cc in config.get(ALL_C_CHANNEL, []):
                if cc[SRC] == node1 and cc[DST] == node2:
                    delay = cc.get(DELAY, cc.get(DISTANCE, 1000) / SPEED_OF_LIGHT)
                    cc_delay.append(delay)
                elif cc[SRC] == node2 and cc[DST] == node1:
                    delay = cc.get(DELAY, cc.get(DISTANCE, 1000) / SPEED_OF_LIGHT)
                    cc_delay.append(delay)

            for cc in config.get(ALL_C_CONNECT, []):
                if (cc[CONNECT_NODE_1] == node1 and cc[CONNECT_NODE_2] == node2) \
                        or (cc[CONNECT_NODE_1] == node2 and cc[CONNECT_NODE_2] == node1):
                    delay = cc.get(DELAY, cc.get(DISTANCE, 1000) / SPEED_OF_LIGHT)
                    cc_delay.append(delay)
            if len(cc_delay) == 0:
                assert 0, q_connect
            cc_delay = np.mean(cc_delay) // 2

