from .mesh_topo import MeshTopo
from .node import BSMNode, QuantumRouter
from ..constants import *


class RouterNetTopo(MeshTopo):
    """Class for generating quantum communication network with quantum routers

    Class RouterNetTopo is the child of class MeshTopo. Quantum routers, BSM
    nodes, quantum  channels, classical channels and timeline for simulation
    could be generated by using this class.

    Attributes:
        bsm_to_router_map (dict[str, list[Node]]): mapping of bsm node to two connected routers
        nodes (dict[str, list[Node]]): mapping of type of node to a list of same type node.
        qchannels (list[QuantumChannel]): list of quantum channel objects in network.
        cchannels (list[ClassicalChannel]): list of classical channel objects in network.
        tl (Timeline): the timeline used for simulation
    """

    _BSM_NAME_TEMPLATE = "BSM.{}.{}"
    _ROUTER_NODE_TYPE = QUANTUM_ROUTER

    def _add_nodes(self, config: dict):
        for node in config[ALL_NODE]:
            seed = node[SEED]
            node_type = node[TYPE]
            name = node[NAME]
            template_name = node.get(TEMPLATE, None)
            template = self.templates.get(template_name, {})

            if node_type == BSM_NODE:
                others = self.bsm_to_router_map[name]
                node_obj = BSMNode(name, self.tl, others, component_templates=template)
            elif node_type == QUANTUM_ROUTER:
                memo_size = node.get(MEMO_ARRAY_SIZE, 0)
                node_obj = QuantumRouter(name, self.tl, memo_size, component_templates=template)
            else:
                raise ValueError(f"Unknown type of node '{node_type}'")

            node_obj.set_seed(seed)
            self.nodes[node_type].append(node_obj)
