name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@1.5.2
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'

  validation:
    if: github.repository == 'sequence-toolbox/SeQUeNCe'
    name: Run Unit Tests
    permissions:
      contents: read
      code-quality: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6

    - name: Install uv and set py version
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Install sequence
      run: uv sync --locked --all-extras --dev --no-editable

    - name: Run tests
      run: uv run pytest --cov=. --cov-report=xml

    - name: Upload coverage report
      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
      uses: actions/upload-code-coverage@v1
      with:
        file: coverage.xml
        language: Python
        label: code-coverage/pytest