name: Mirror to GitLab
on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]
  delete:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_KEY }}
          GITLAB_REPO: ${{ secrets.GITLAB_URL }}
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO}"
          git push --force --prune --tags gitlab "refs/remotes/origin/*:refs/heads/*"